class AppAssets {
  AppAssets();
  static final String otpSuccessfulIcon = 'assets/images/successful_otp.png';
  static final String bgImage1 = 'assets/background.png';
  static final String logo = 'assets/youtubelogo.png';
  static final String image1 = 'assets/mqdefault.png';
  static final String bgImage2 = 'assets/authentication.png';
  static final String playlist = 'assets/svg/playlists.svg';
  static final String library = 'assets/svg/playlist.svg';
  static final String search = 'assets/svg/search.svg';
  static final String setting = 'assets/svg/setting.svg';
  static final String globe = 'assets/globe.png';
  static final String previous = 'assets/svg/previous.svg';
  static final String play = 'assets/svg/play-icon.svg';
  static final String next = 'assets/svg/next.svg';
  static final String mpFile = 'assets/svg/mp_file.svg';
  static final String djMixer = 'assets/svg/dj_mixer.svg';
  static final String radio = 'assets/svg/radio.svg';
  static final String radioWave = 'assets/svg/radio_wave.svg';
  static final String line = 'assets/svg/line.svg';
  static final String favorite = 'assets/svg/heart.svg';
  static final String rect = 'assets/rect.png';
  static final String shuffle = 'assets/svg/shuffle.svg';
  static final String repeat = 'assets/svg/repeat.svg';
  static final String share = 'assets/svg/share.svg';
  static final String dot = 'assets/svg/dot.svg';
  static final String music = 'assets/svg/music.svg';
  static final String record = 'assets/svg/record.svg';
  static final String split = 'assets/svg/split.svg';
  static final String plan = 'assets/svg/plan.svg';
}
